### ISSUE TITLE
EC2 error

### ISSUE THREAD

**Issue by cheavyio** [trailofbits/algo#116]
Attempts to use EC2 crash here for me - 
[ABCD...]: ./algo: line 106: read: -i: invalid option

**Comment by defunctio** [comment]
I assume you are on osx, this is due to an older bash version. I'm not sure what version -i was implemented in but upgrading bash should resolve the issue.

**Comment by cheavyio** [comment]
Yes, it is OS X.  Thanks!

**Comment by dguido** [comment]
Ugh damn it OS X. Is there a workaround available for this? I think the majority of our users run Algo from OS X.

**Comment by defunctio** [comment]
We can use bash parameter expansion to get around this

ex:
```
read -p "ssh key: " name
name=${key:-~/.ssh/id_rsa}
echo $key
```

**Comment by defunctio** [comment]
@cheavyio changes regarding this issue have been pushed to the ec2updates branch - commit e5779e64d68802da67b91283edcb29a47e0c9731 . If you or someone else could test that this works on OSX now we can merge it to master. 
Thanks

**Comment by dguido** [comment]
I won't be able to test it for a while. Anyone else?

**Comment by WIZARDISHUNGRY** [comment]
@dguido works for me.

**Comment by dbrwn** [comment]
On ec2updates branch, both commits e5779e64d68802da67b91283edcb29a47e0c9731 and 784859572c823e9b2e33606b05ca332e66f29737 fail for me on OSX / macOS Sierra.

`16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64`



Failure occurs here:
```
TASK [cloud-ec2 : Locate official Ubuntu 16.04 AMI for region] *****************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'env' is undefined\n\nThe error appears to have been in '/Users/dbrown/Code/external/algo/roles/cloud-ec2/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Locate official Ubuntu 16.04 AMI for region\n  ^ here\n"}
```

**Comment by defunctio** [comment]
@dbrwn Sorry about that, I should have tested before I pushed the commit. I didn't notice the syntax error and I've been working on another feature branch. Check the latest commit 475365007dacde59d54faa112c619ed63b8a812b

**Comment by dbrwn** [comment]
@defunctio commit 475365007dacde59d54faa112c619ed63b8a812b resolves the args problem I mentioned above, as well as the original 'read -i' problem that is the subject of this issue.
I am still having a problem after the instance launches (in Post-provisioning tasks) but I'll check if there's an existing issue and create a new one if needed.
